name: Generate README

on:
  push:
    branches:
      - main

permissions:
    contents: write

jobs:
  notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create README
        run: make

      - name: README Update - Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5 
        with:
          file_pattern: 'README.md'

          commit_message: "docs(readme): update to lastest version"